// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"at-kratos/internal/biz"
	"at-kratos/internal/conf"
	"at-kratos/internal/data"
	"at-kratos/internal/server"
	"at-kratos/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	signupLogRepo := data.NewSignupLogRepo(dataData, logger)
	signupLogUseCase := biz.NewSignupLogUseCase(signupLogRepo, logger)
	loggerService, cleanup2 := service.NewLoggerService(signupLogUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, loggerService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
