// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: logger/v1/logger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 元信息
type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip        string  `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                 // ip地址
	Platform  string  `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`     // 平台
	Timestamp float64 `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 请求毫秒时间戳
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Meta) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Meta) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 分页查询条件
type PageQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页行数
}

func (x *PageQuery) Reset() {
	*x = PageQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageQuery) ProtoMessage() {}

func (x *PageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageQuery.ProtoReflect.Descriptor instead.
func (*PageQuery) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{1}
}

func (x *PageQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageQuery) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SignupLogDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyUuid  string  `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`    // 企业uuid
	OperatorUuid string  `protobuf:"bytes,2,opt,name=operator_uuid,json=operatorUuid,proto3" json:"operator_uuid,omitempty"` // 操作人uuid
	OperatorName string  `protobuf:"bytes,3,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"` // 操作人名称
	Way          string  `protobuf:"bytes,4,opt,name=way,proto3" json:"way,omitempty"`                                       // 登录方式
	Ip           string  `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`                                         // ip地址
	Platform     string  `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`                             // 平台
	Extra        []byte  `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`                                   // 其他内容(2进制)
	CreatedTime  float64 `protobuf:"fixed64,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`  // 创建毫秒时间戳
}

func (x *SignupLogDTO) Reset() {
	*x = SignupLogDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupLogDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupLogDTO) ProtoMessage() {}

func (x *SignupLogDTO) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupLogDTO.ProtoReflect.Descriptor instead.
func (*SignupLogDTO) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{2}
}

func (x *SignupLogDTO) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *SignupLogDTO) GetOperatorUuid() string {
	if x != nil {
		return x.OperatorUuid
	}
	return ""
}

func (x *SignupLogDTO) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *SignupLogDTO) GetWay() string {
	if x != nil {
		return x.Way
	}
	return ""
}

func (x *SignupLogDTO) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SignupLogDTO) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SignupLogDTO) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *SignupLogDTO) GetCreatedTime() float64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

// 请求添加登录日志
type SignupLogPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyUuid  string `protobuf:"bytes,1,opt,name=company_uuid,json=companyUuid,proto3" json:"company_uuid,omitempty"`    // 企业uuid
	OperatorUuid string `protobuf:"bytes,2,opt,name=operator_uuid,json=operatorUuid,proto3" json:"operator_uuid,omitempty"` // 操作人uuid
	OperatorName string `protobuf:"bytes,3,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"` // 操作人名称
	Way          string `protobuf:"bytes,4,opt,name=way,proto3" json:"way,omitempty"`                                       // 登录方式
	Extra        []byte `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`                                   // 其他内容(2进制)
	Meta         *Meta  `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`                                     // 元信息
}

func (x *SignupLogPutRequest) Reset() {
	*x = SignupLogPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupLogPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupLogPutRequest) ProtoMessage() {}

func (x *SignupLogPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupLogPutRequest.ProtoReflect.Descriptor instead.
func (*SignupLogPutRequest) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{3}
}

func (x *SignupLogPutRequest) GetCompanyUuid() string {
	if x != nil {
		return x.CompanyUuid
	}
	return ""
}

func (x *SignupLogPutRequest) GetOperatorUuid() string {
	if x != nil {
		return x.OperatorUuid
	}
	return ""
}

func (x *SignupLogPutRequest) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *SignupLogPutRequest) GetWay() string {
	if x != nil {
		return x.Way
	}
	return ""
}

func (x *SignupLogPutRequest) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *SignupLogPutRequest) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 返回添加登录日志
type SignupLogPutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 状态码:100=成功
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 失败消息
}

func (x *SignupLogPutReply) Reset() {
	*x = SignupLogPutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupLogPutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupLogPutReply) ProtoMessage() {}

func (x *SignupLogPutReply) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupLogPutReply.ProtoReflect.Descriptor instead.
func (*SignupLogPutReply) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{4}
}

func (x *SignupLogPutReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SignupLogPutReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 请求登录日志列表
type SignupLogGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip       string     `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`             // ip地址
	Platform string     `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // 平台
	Way      string     `protobuf:"bytes,3,opt,name=way,proto3" json:"way,omitempty"`           // 登录方式
	Pq       *PageQuery `protobuf:"bytes,4,opt,name=pq,proto3" json:"pq,omitempty"`             // 分页查询
}

func (x *SignupLogGetRequest) Reset() {
	*x = SignupLogGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupLogGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupLogGetRequest) ProtoMessage() {}

func (x *SignupLogGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupLogGetRequest.ProtoReflect.Descriptor instead.
func (*SignupLogGetRequest) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{5}
}

func (x *SignupLogGetRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SignupLogGetRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SignupLogGetRequest) GetWay() string {
	if x != nil {
		return x.Way
	}
	return ""
}

func (x *SignupLogGetRequest) GetPq() *PageQuery {
	if x != nil {
		return x.Pq
	}
	return nil
}

// 返回登录日志列表
type SignupGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                               // 状态码:100=成功
	Msg        string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                  // 失败消息
	Rows       []*SignupLogDTO `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`                                // 列表数据
	TotalCount int64           `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总行数
}

func (x *SignupGetReply) Reset() {
	*x = SignupGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logger_v1_logger_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignupGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupGetReply) ProtoMessage() {}

func (x *SignupGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_logger_v1_logger_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupGetReply.ProtoReflect.Descriptor instead.
func (*SignupGetReply) Descriptor() ([]byte, []int) {
	return file_logger_v1_logger_proto_rawDescGZIP(), []int{6}
}

func (x *SignupGetReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SignupGetReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SignupGetReply) GetRows() []*SignupLogDTO {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *SignupGetReply) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_logger_v1_logger_proto protoreflect.FileDescriptor

var file_logger_v1_logger_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x67,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3c, 0x0a, 0x09, 0x50, 0x61,
	0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xf2, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x67,
	0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x44, 0x54, 0x4f, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x77, 0x61, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xc5, 0x01,
	0x0a, 0x13, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x77, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x19, 0x0a, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4c,
	0x6f, 0x67, 0x50, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x6f, 0x0a, 0x13, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x77, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x02, 0x70, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x02, 0x70,
	0x71, 0x22, 0x7a, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x4c, 0x6f, 0x67, 0x44, 0x54, 0x4f, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x89, 0x01,
	0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3a, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x5f, 0x6c, 0x6f,
	0x67, 0x73, 0x12, 0x14, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75,
	0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0e, 0x70,
	0x75, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x14, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x74, 0x2d,
	0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logger_v1_logger_proto_rawDescOnce sync.Once
	file_logger_v1_logger_proto_rawDescData = file_logger_v1_logger_proto_rawDesc
)

func file_logger_v1_logger_proto_rawDescGZIP() []byte {
	file_logger_v1_logger_proto_rawDescOnce.Do(func() {
		file_logger_v1_logger_proto_rawDescData = protoimpl.X.CompressGZIP(file_logger_v1_logger_proto_rawDescData)
	})
	return file_logger_v1_logger_proto_rawDescData
}

var file_logger_v1_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_logger_v1_logger_proto_goTypes = []interface{}{
	(*Meta)(nil),                // 0: Meta
	(*PageQuery)(nil),           // 1: PageQuery
	(*SignupLogDTO)(nil),        // 2: SignupLogDTO
	(*SignupLogPutRequest)(nil), // 3: SignupLogPutRequest
	(*SignupLogPutReply)(nil),   // 4: SignupLogPutReply
	(*SignupLogGetRequest)(nil), // 5: SignupLogGetRequest
	(*SignupGetReply)(nil),      // 6: SignupGetReply
}
var file_logger_v1_logger_proto_depIdxs = []int32{
	0, // 0: SignupLogPutRequest.meta:type_name -> Meta
	1, // 1: SignupLogGetRequest.pq:type_name -> PageQuery
	2, // 2: SignupGetReply.rows:type_name -> SignupLogDTO
	5, // 3: LoggerService.get_signup_logs:input_type -> SignupLogGetRequest
	3, // 4: LoggerService.put_signup_log:input_type -> SignupLogPutRequest
	6, // 5: LoggerService.get_signup_logs:output_type -> SignupGetReply
	4, // 6: LoggerService.put_signup_log:output_type -> SignupLogPutReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logger_v1_logger_proto_init() }
func file_logger_v1_logger_proto_init() {
	if File_logger_v1_logger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logger_v1_logger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logger_v1_logger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logger_v1_logger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupLogDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logger_v1_logger_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupLogPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logger_v1_logger_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupLogPutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logger_v1_logger_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupLogGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logger_v1_logger_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignupGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logger_v1_logger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logger_v1_logger_proto_goTypes,
		DependencyIndexes: file_logger_v1_logger_proto_depIdxs,
		MessageInfos:      file_logger_v1_logger_proto_msgTypes,
	}.Build()
	File_logger_v1_logger_proto = out.File
	file_logger_v1_logger_proto_rawDesc = nil
	file_logger_v1_logger_proto_goTypes = nil
	file_logger_v1_logger_proto_depIdxs = nil
}
