// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: logger/v1/logger.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoggerServiceClient is the client API for LoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggerServiceClient interface {
	// 查询登录日志
	GetSignupLogs(ctx context.Context, in *SignupLogGetRequest, opts ...grpc.CallOption) (*SignupGetReply, error)
	// 添加登录日志
	PutSignupLog(ctx context.Context, in *SignupLogPutRequest, opts ...grpc.CallOption) (*SignupLogPutReply, error)
}

type loggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerServiceClient(cc grpc.ClientConnInterface) LoggerServiceClient {
	return &loggerServiceClient{cc}
}

func (c *loggerServiceClient) GetSignupLogs(ctx context.Context, in *SignupLogGetRequest, opts ...grpc.CallOption) (*SignupGetReply, error) {
	out := new(SignupGetReply)
	err := c.cc.Invoke(ctx, "/LoggerService/get_signup_logs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerServiceClient) PutSignupLog(ctx context.Context, in *SignupLogPutRequest, opts ...grpc.CallOption) (*SignupLogPutReply, error) {
	out := new(SignupLogPutReply)
	err := c.cc.Invoke(ctx, "/LoggerService/put_signup_log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServiceServer is the server API for LoggerService service.
// All implementations must embed UnimplementedLoggerServiceServer
// for forward compatibility
type LoggerServiceServer interface {
	// 查询登录日志
	GetSignupLogs(context.Context, *SignupLogGetRequest) (*SignupGetReply, error)
	// 添加登录日志
	PutSignupLog(context.Context, *SignupLogPutRequest) (*SignupLogPutReply, error)
	mustEmbedUnimplementedLoggerServiceServer()
}

// UnimplementedLoggerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoggerServiceServer struct {
}

func (UnimplementedLoggerServiceServer) GetSignupLogs(context.Context, *SignupLogGetRequest) (*SignupGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignupLogs not implemented")
}
func (UnimplementedLoggerServiceServer) PutSignupLog(context.Context, *SignupLogPutRequest) (*SignupLogPutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutSignupLog not implemented")
}
func (UnimplementedLoggerServiceServer) mustEmbedUnimplementedLoggerServiceServer() {}

// UnsafeLoggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggerServiceServer will
// result in compilation errors.
type UnsafeLoggerServiceServer interface {
	mustEmbedUnimplementedLoggerServiceServer()
}

func RegisterLoggerServiceServer(s grpc.ServiceRegistrar, srv LoggerServiceServer) {
	s.RegisterService(&LoggerService_ServiceDesc, srv)
}

func _LoggerService_GetSignupLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupLogGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).GetSignupLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoggerService/get_signup_logs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).GetSignupLogs(ctx, req.(*SignupLogGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggerService_PutSignupLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupLogPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).PutSignupLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoggerService/put_signup_log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).PutSignupLog(ctx, req.(*SignupLogPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoggerService_ServiceDesc is the grpc.ServiceDesc for LoggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LoggerService",
	HandlerType: (*LoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_signup_logs",
			Handler:    _LoggerService_GetSignupLogs_Handler,
		},
		{
			MethodName: "put_signup_log",
			Handler:    _LoggerService_PutSignupLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger/v1/logger.proto",
}
